name: marc2d
description: Móvil Android reciclado como centralita domótica

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10000

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  teledart: 0.0.39
  freezed_annotation: 0.7.1
  json_serializable: 3.3.0
  url_launcher: 5.4.2
  package_info: ^0.4.0+16
  intl: ^0.16.1
  flutter_secure_storage: ^3.3.3
  flutter_bloc: 3.2.0
  camera: 0.5.7+4
  path_provider: 1.6.5
  torch_compat: 1.0.2
  light: 0.1.1
  sensors: 0.4.2
  battery: 0.3.1+10
  device_info: 0.4.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: 0.17.9
  lint: ^1.1.1
  build_runner: 1.8.1
  freezed: 0.10.7

flutter:
  uses-material-design: true
  fonts:
    - family: VT323
      fonts:
        - asset: assets/VT323-Regular.ttf